### PR TITLE
AttributeError: np.float_ fixed

### PR DESCRIPTION
**Pull request by shamalgithub**
changed the  NDArray[np.float_]  to  NDArray[np.float64] to be compatible with Numpy version 2.0

### CODE REVIEW

**Comment by Kerwin-Buijsman** [comment]
I manually changed the code in my installed Prophet package to solve the AttributeError: np.float_ error. It would be nice if this PR gets approved and the new changes are released :)

**Comment by pcpp94** [comment]
This is a bit of a hassle - can someone approve this PR?

**Comment by breimers** [comment]
Is there a planned release to PyPi of a new version with these changes?

**Comment by tisba** [comment]
Sorry for the ping, @tcuongd, but there are so many issues for this issue and several open PRs to fix it… maybe we can get this one in somehow? Unless I'm overlooking something, this should be a rather trivial and save change.

**Comment by cameronbcote** [comment]
would this work?

numpy as np
np.float_ = np.float64

**Comment by tisba** [comment]
Thanks for merging, @WardBrian. Is there any chance to get a release cut soonish? I couldn't find a milestone or something and it has been a while since the last release :)

**Comment by WardBrian** [comment]
I have commit rights but haven't run a release myself -- @tcuongd has been managing those, so let's ask him

**Comment by WardBrian** [comment]
@tcuongd I see a 1.1.6 here, but not on PyPI -- did the release successfully complete?

**Comment by tcuongd** [comment]
It seems like PyPI has increased their security for releases. Github Actions now has to be added as a "trusted publisher" for the PyPI upload to work, which only the owners of the package (the original authors) can do. I've asked Ben, hopefully he gets back to us soon. In the meantime, the new binaries have been attached to the release note (https://github.com/facebook/prophet/releases/tag/v1.1.6-patched).

**Pull request merged**
