### PR TITLE
Fix exception causes in 2 modules

### PR DESCRIPTION
**Pull request by cool-RR**

### CODE REVIEW

**Comment by cool-RR** [comment]
I signed the CLA now.

**Comment by bletham** [comment]
Thanks for the fix!

**Comment by cool-RR** [comment]
@bletham  Thanks for the quick merge! Would you be interested in this change in more modules?

**Comment by bletham** [comment]
@cool-RR Definitely, go for it! I actually didn't know about this syntax until seeing this PR.

**Comment by cool-RR** [comment]
Hey, looks like there are no more places with this problem :)

**Comment by bletham** [comment]
Thanks for checking :-)

**Pull request merged**
