### PR TITLE
Fix bug that many extra regressors cause an predict error after pickle/unpickling

### PR DESCRIPTION
**Pull request by Gedevan-Aleksizde**
I change the extra_regressors dict object to OrderedDict in the Prophet class.

https://github.com/facebook/prophet/issues/643

### CODE REVIEW

**Comment by bletham** [comment]
Perfect, thanks for the fix!

**Comment by danielvdende** [comment]
@bletham Sorry if this isn't the right place to ask this. I tried to find a release roadmap, couldn't find any. When could we expect this fix to be released? I can work around it with an install from github, but it would be much nicer (of course) if we could have a pypi package :-)

**Comment by bletham** [comment]
We will push this early next week :-)

**Comment by danielvdende** [comment]
@bletham any sign of that release? :-)

**Comment by bletham** [comment]
@danielvdende Sorry for the delay, we wanted to push it to PyPI at the same time as the new R version, but it has been more than two weeks and we still haven't gotten CRAN to push out the new R release so we finally just pushed it to PyPI. So you'll find it now.

**Pull request merged**
