### PR TITLE
Remove pystan, leave backend abstraction for now

### LINKED ISSUE #2041: Remove `pystan` backend, move to `cmdstanpy`
### Context

Pystan 3+ makes some breaking changes to Prophet python package:
* MAP estimation is removed.
* Windows support is removed.

We've been continuing to use Pystan 2.19.1.1, but this is only supported up to Python 3.8 and no longer receives development. Many of our issues also relate to pystan issues, which will become harder to debug over time and may need hacky patches.

The current installation process with pystan is as follows:

**Mac OS / Linux**

* End users usually use prophet from PyPi.
* End user must install `pystan=2.19.1.1` first, as it is required for building the wheel
* End user installs `prophet`, which includes compiling the pystan model on their machine.

**Windows**

* End users usually use prophet from `conda-forge`.

### Proposal

* Use `cmdstan` + `cmdstanpy` to build binary distributions for Pypi (using Github Actions) and conda-forge, across all platforms. 
  * Packaging pre-compiled stan models per platform + python version means the end-user does not need to perform the build process on their machine. They won't even need their own `cmdstan` installation since we will package the necessary executables into Prophet itself. 
  * Only the lightweight wrapper library `cmdstanpy` is required as a dependency.
* Remove the dependency on `pystan` altogether.

This should **not** change how end-users typically interact with the Prophet package. The general flow of

```python
m = Prophet()
m.fit(df)
future = m.make_future_dataframe()
m.predict(future)
```

will remain unchanged, and all other diagnostic functions will work as normal. 

It's just that behind the scenes, the model object will now be a `cmdstanpy` object rather than a `pystan` one. The argument `stan_backend='PYSTAN'` will also be deprecated. This will affect end users who retrieve the actual `pystan` object and work with it directly, but we expect this to be the minority.

We have already refactored the [setup.py](https://github.com/facebook/prophet/blob/master/python/setup.py) script to accomodate this new process (it currently supports both `pystan 2.19.1.1` and `cmdstanpy` for backwards compatibility). 
We have also [built and tested PyPi wheels](https://github.com/facebook/prophet/actions/runs/1299679630) for macOS and Linux for Python versions 3.6-3.8. If you follow the instructions [here](https://github.com/facebook/prophet/issues/664#issuecomment-913161698), you can test these binary distributions on your machine.

### Work required

For the next minor release (prophet 1.1.0), we should consider the following:

- [ ] Update existing conda build scripts to use the `cmdstan` + `cmdstanpy` backend.
- [ ] Remove the `pystan` model compilation from the build process and remove `pystan` as a Prophet dependency.
- [x] (Optional) Add support for a Windows wheel on PyPi.

### PR DESCRIPTION
**Pull request by WardBrian**
Closes #2041, follows on from #2088 

This does not refactor the `IStanBackend` class or anything like that yet. It just removes pystan from the requirements.txt, and deletes the imports of it

### CODE REVIEW

**Comment by WardBrian** [comment]
After this is merged you the build_wheel can run and build for python 3.6-3.10. Until PyPi is updated that link will be the best bet

**Comment by jlopezpena** [comment]
This is great, I can confirm checking out this PR solves all the build issues on Mac with python 3.9+. It would be great to have this merged, and perhaps a new pypi packaged released, as the fact that the "official" pypi release doesn't work with any recent python is not great. IMO, the code refactoring can be postponed as it will not alter any functionality.

**Comment by WardBrian** [comment]
I think leaving the backend code for now could even be useful if things like #1973 get another look

**Comment by akosfurton** [comment]
This looks great!

Looking forward to this being merged and Prophet released to PyPi again

**Comment by WardBrian** [comment]
@tcuongd are you able to review this? I know there are some permissions issues blocking a PyPi release as well, but this is one of the final roadblocks as I understand

**Comment by nlhkh** [comment]
Thank you! I think Prophet really need this because pystan is really problematic to install.

**Comment by nicolaerosia** [comment]
@tcuongd kind ping :)

**Comment by tcuongd** [comment]
Yep this LGTM, thanks heaps! I'll trigger a `wheel.yml` workflow after the merge to test the 3.9-3.10 wheels as well.

**Comment by tcuongd** [comment]
Successfully built wheels without pystan: https://github.com/facebook/prophet/actions/runs/2275140778
Huge thanks to @WardBrian!

**Comment by ShantanuKumar** [comment]
Does this mean we will soon have a pypi release?

**Pull request merged**
