### PR TITLE
Implement Cross Validation metrics for Forecasts in Python

### PR DESCRIPTION
**Pull request by toddbot**
(note I added and closed a PR by accident on the main prophet github...apologies!)
In the spirit of #384 I'd like to modify the diagnostics.py file to produce a summary of fitting metrics so that analysts can quickly optimize their implementation directly from the Prophet interface. However, if this is has already been in done in Python let me know and I'll maybe check out something else!

### CODE REVIEW

**Comment by teramonagi** [comment]
Thank you for your help in advance :)

**Comment by teramonagi** [comment]
@toddbot 
Finally, The code of R version was merged in [this PR](https://github.com/facebook/prophet/pull/384#issuecomment-355698473)!

**Comment by bletham** [comment]
Could you rebase this commit on top of v0.3 branch and merge into there instead of master please? Then this looks good to go in.

**Comment by bletham** [comment]
Superseded by #414

**Pull request closed without merging**
