### PR TITLE
Disable-uncertainty-estimation-in-R 

### PR DESCRIPTION
**Pull request by ryankarlos**
- [x] Fixes issue #1082 
- [x] Tests pass in `testthat` folder

### CODE REVIEW

**Comment by ryankarlos** [comment]
@bletham Do we need extra tests for these - the python additions don't seem to have any additional ones to test when uncertainty is set to 0 of False

**Comment by bletham** [comment]
This looks great!
Yeah we should definitely add a couple tests. One that does fit/predict and verifies that the column set is correct would be sufficiently to cover all of the changes in the main class, and then a second that does a cross validation would cover the changes there. As you note this should be done for Py as well so I'll merge this now and that can be a separate PR/ pair of PRs.

**Comment by ryankarlos** [comment]
@bletham thanks will create issues and separate PRs for this

**Comment by bletham** [comment]
Awesome, we can use #1082 still for this still if you'd like.

**Comment by ryankarlos** [comment]
@bletham sure, fine by me

**Pull request merged**
