### PR TITLE
Update plot.py

### PR DESCRIPTION
**Pull request by tomthepeach**
Removed depreciated/unnecessary datetime conversion

### CODE REVIEW

**Comment by tcuongd** [comment]
Could you please provide some example plots from your branch to validate that the functionality is still working as intended, thanks!

**Comment by tomthepeach** [comment]
image

**Comment by tomthepeach** [comment]
This is using my fork built locally in a venv

**Comment by tomthepeach** [comment]
This solves issue  #2492 https://github.com/facebook/prophet/issues/2492

**Comment by tomthepeach** [comment]
@tcuongd  Ok to merge?

**Review by tcuongd — APPROVED** [review]
Thanks for this and sorry for the long review lag.

**Pull request merged**
