### PR TITLE
pass ... from dyplot.prophet to dygraph::dygraph, addresses #1158

### PR DESCRIPTION
**Pull request by adrfantini**
This PR addresses #1158, passing `...` from `dyplot.prophet` to `dyplot.prophet` to allow for additional parameters such as `main` to be set.

Apparently my text editor removed a bunch of spaces at the end of the lines, hence the large number of deletions. Let me know if this constitutes a problem.

This is one of my first PRs, please be understanding if I screwed something up!

### CODE REVIEW

**Comment by bletham** [comment]
This LGTM! Were you able to test that it works? You can install the local version with
```
devtools::install('.')
```
from inside the R directory. And then if you could post some code that demonstrates it working that'd be great!

**Comment by adrfantini** [comment]
Mh, after the local install funnily enough I can't use prophet:
```R
# From dyplot.prophet's manual page
library(prophet)
history <- data.frame(
      ds = seq(as.Date('2015-01-01'), as.Date('2016-01-01'), by = 'd'),
      y = sin(1:366/200) + rnorm(366)/10)
m <- prophet(history)
future <- make_future_dataframe(m, periods = 365)
forecast <- predict(m, future)
```
Returns this error:
```
Error in predict_seasonal_components(object, df) :
  object 'uncertainty.samples' not found
```
This also happens with other tests.

**Comment by bletham** [comment]
Ah, sorry about that, the R version on github was briefly broken. We landed the fix on Wednesday (https://github.com/facebook/prophet/commit/f4d997e0acb286507182cb9f5aefeaaa17ff675b). You'll have to rebase your commit on top of that for it to work.

**Comment by adrfantini** [comment]
Mh, I'm still getting (example from `dyplot.prophet`'s docs):
```R
> dyplot.prophet(m, forecast)
Error in uncertainty && x$uncertainty.sampes :
  invalid 'y' type in 'x && y'
```

**Comment by bletham** [comment]
mm, thanks for pointing this out, it looks like there is a typo in that line, `x$uncertainty.sampes` should be `x$uncertainty.samples`. If you make that substitution it should work, and sorry again for the bugs here; that PR seems to have had a few and wasn't tested well before it went in.

**Comment by janithwanni** [comment]
Did anyone merge this PR yet? Because I had the same issue of adding a title into a dygraph.

**Pull request merged**
