### PR TITLE
Error metrics python v2

### PR DESCRIPTION
**Pull request by toddbot**
This is a version of the pull request on https://github.com/facebook/prophet/pull/399. The new base branch is on v0.3. I saw the suggestion from @teramonagi to change interface to match R. @bletham Happy to do that if that also makes sense to you.

### CODE REVIEW

**Comment by teramonagi** [comment]
I think that we need
- individual metrics function (e.g. `me`, `mae`, `mpe`)
- metrics functions take Simulated Forecast Object as a argument

It might be helpful for you to see the following code: https://github.com/facebook/prophet/pull/384/files#diff-e78e1108bb37c00e8ee57983b5a5987bR110

**Comment by teramonagi** [comment]
I forgot to mention about test.
I wrote unit test in R like [this](https://github.com/facebook/prophet/blob/v0.3/R/tests/testthat/test_metrics.R).
You can add your unit test file to [this directory](https://github.com/facebook/prophet/tree/v0.3/python/fbprophet/tests) in Python.

**Comment by bletham** [comment]
This is good, I'll merge this as-is and I can add the unit tests.

**Comment by bletham** [comment]
Thanks!

**Pull request merged**
