### PR TITLE
Update forecaster.py

### PR DESCRIPTION
**Pull request by LiceyMaxim**
make_future_dataframe
Change description, removed unnecessary comments and operations

### CODE REVIEW

**Comment by LiceyMaxim** [comment]
Add Facebook CLA

**Comment by tcuongd** [comment]
It seems like the tests are failing. Could you take a look and see if it's related to your change? Thanks!

**Comment by LiceyMaxim** [comment]
@tcuongd Could you please check my pr?

**Comment by tcuongd** [comment]
Thanks, could you please update the description with what scenarios this would solve and the before/after? Or do you mainly just want to get rid of the `inplace` operation? I see you've also removed the `dates = dates[:periods]` line.

**Pull request closed without merging**
