### PR TITLE
add setup_requires on pystan so build requirements are in the metadata

### PR DESCRIPTION
**Pull request by CJ-Wright-Citadel**
It seems that pystan is a build time requirement (since it is used in the `from prophet.models import StanBackendEnum` import in `build_models`). It seems however, that it isn't listed in the `setup_requires` so that the installing system doesn't know that it is a build requirement.

This PR adds the needed pystan build requirement.

### CODE REVIEW

**Review by hildobby — APPROVED** [review]
I think this is a very needed PR given the current incompability with pystan 3!

**Comment by Djailla** [comment]
Hello, I strongly approve this is a needed PR !

**Comment by tcuongd** [comment]
Thanks for this! I'm just wondering why this wasn't done in the first place, not sure if there was a particular reason for it.

I'll dig a little further, but in the meantime @bletham do you remember why off the top of your head?

**Comment by tcuongd** [comment]
Heya, the latest changes to setup.py as a part of this PR: https://github.com/facebook/prophet/pull/2010/files
covers the core problem here.

Instead of using setuptool's `setup_requires`, we've gone for the recommended approach of specifying the build system requirements in a `pyproject.toml`. Now the "proper" way to build prophet from source will be to do `python -m build .`.

Hopefully most end users won't need to do that though, since the PR also allows us to build wheels for different OS and python versions, so Prophet should mostly just work out of the box (pending changes needed for Windows and python 3.9).

I'll close this now, but if you have any other questions let me know!

**Pull request closed without merging**
