### PR TITLE
Modifying the way important links are displayed in readme.md

### PR DESCRIPTION
**Pull request by kshithijiyer**

### CODE REVIEW

**Comment by kshithijiyer** [comment]
I personally feel that it's better to have hyperlinks instead of copy pasting the URL. If the user is interested he/she'll open it and read it else he/she'll neglect it. And it looks alot clean when you look at the me file.

**Comment by bletham** [comment]
hm I think it is nice to be able to see what the URL is before clicking it to get some sense of where you're going. But when you said "instead of copy pasting the URL" - is it not showing up for you as a hyperlink? At least in my browser I see all of these as hyperlinks with the address as their text. Are you seeing something different?
screenshot

**Comment by kshithijiyer** [comment]
No. I am seeing the same thing, and this looks kind of shabby. I feel if people want to see what's in the link they wouldn't really care where it is stored.

**Comment by kshithijiyer** [comment]
So what should we do finally should we change it or should we keep it as it is?

**Comment by bletham** [comment]
Sorry, I do like to see the URLs and so I'm inclined to leave this out unless it starts to effect usability of the site.

**Pull request closed without merging**
