### PR TITLE
10X faster predict by replacing DataFrame with dict

### PR DESCRIPTION
**Pull request by orenmatar**
Profiling the predict code yielded this result:
before_change

Evidently about 90% of the predict time is spent on either the init of a DataFrame or its __getitem__ method, both are notoriously slow.
A very simple change from dataframe to dict in sample_model and sample_model_vectorized has no risk and implications beyond sample_posterior_predictive since the df is converted to a dict there anyway.
Profiling after the change gives:

after_change

and in runtime it was reduced from ~300ml to ~38ml on a local test

### CODE REVIEW

**Comment by nicolaerosia** [comment]
@tcuongd can we please merge this and release a new version with wheels for python 3.11 as well?

**Comment by orenmatar** [comment]
@tcuongd any updates on this? It should be really easy to integrate and yields a big runtime improvement

**Review by tcuongd — APPROVED** [review]
Wow great find, thanks heaps! Yeah I think changing the return type for these internal functions is fine, we just need to make it clear which functions are affected in the release notes.

**Comment by tcuongd** [comment]
For some reason CI didn't kick off, I'll take a look later

**Comment by tcuongd** [comment]
@orenmatar Do you mind just signing the CLA? Thanks!

**Comment by orenmatar** [comment]
@tcuongd Signed it just now

**Pull request merged**
