### PR TITLE
suppress plotly error logging 

### PR DESCRIPTION
**Pull request by ryankarlos**
closes issue #1242

### CODE REVIEW

**Comment by bletham** [comment]
Thanks for the PR!
Changing the logger to be different than that of the main class is great, but my preference would be to not set the logging level for it inside the package. That would be better left to the user, who can add that line to their script if they want to suppress the logging. Does that work for your use?

**Comment by bletham** [comment]
See my comment in #1336 for how one can set the logging level when using the package.

I do like having these messages by default to avoid confusion with users over why the plot isn't working (especially since plotly is not included in the package requirements and so will not be automatically installed by pip).

**Comment by ryankarlos** [comment]
Thanks @bletham - sure yes that works for me

**Comment by bletham** [comment]
To be clear: the renamed logger I think is great and allows for setting levels independently, so it's just a matter of removing the setLevel command

**Comment by ryankarlos** [comment]
ok just removed the setLevel command

**Comment by bletham** [comment]
Perfect, this works great.
If you do
```
from fbprophet import Prophet
```
without plotly installed, you see the message `Importing plotly failed. Interactive plots will not work.`. If you do
```
import logging
logger = logging.getLogger('fbprophet.plot')
logger.setLevel(logging.CRITICAL)
from fbprophet import Prophet
```
then that message is suppressed, but the logging from the Prophet class is not.

**Comment by ryankarlos** [comment]
Thanks @bletham !

**Comment by extrememike** [comment]
> import logging
> logger = logging.getLogger('fbprophet.plot')
> logger.setLevel(logging.CRITICAL)
> from fbprophet import Prophet

@bletham do you have to rename the logger every time? or what this supposed to be addressed for lates version. Just installed 'fbprophet=0.7.1=py38h7ae7562_0'  but the plotly message is still showing up. Thanks

**Comment by bletham** [comment]
@extrememike you would need to use this code blurb every time (or install plotly):
```
import logging
logger = logging.getLogger('fbprophet.plot')
logger.setLevel(logging.CRITICAL)
from fbprophet import Prophet
```
The only other option would be to locally edit the code to remove the warning.

**Pull request merged**
