### PR TITLE
Attempt to use macOS xlarge runner for Apple Silicon wheels

### PR DESCRIPTION
**Pull request by tcuongd**
* https://github.com/actions/runner-images/issues/8439
* Not sure if these paid runners are available for the prophet project

### CODE REVIEW

**Comment by tcuongd** [comment]
@WardBrian We're running into this error when repairing the Apple Silicon wheels:

```
  Fixing: /private/var/folders/df/1dm_t2rx0054k7bw1g_7nyl80000gn/T/cibw-run-umw8ffop/cp38-macosx_arm64/built_wheel/prophet-1.1.4-py3-none-macosx_11_0_arm64.whl
  Traceback (most recent call last):
    File "/private/var/folders/df/1dm_t2rx0054k7bw1g_7nyl80000gn/T/cibw-run-umw8ffop/cp38-macosx_arm64/build/venv/bin/delocate-wheel", line 8, in <module>
      sys.exit(main())
    File "/private/var/folders/df/1dm_t2rx0054k7bw1g_7nyl80000gn/T/cibw-run-umw8ffop/cp38-macosx_arm64/build/venv/lib/python3.8/site-packages/delocate/cmd/delocate_wheel.py", line 127, in main
      copied = delocate_wheel(
    File "/private/var/folders/df/1dm_t2rx0054k7bw1g_7nyl80000gn/T/cibw-run-umw8ffop/cp38-macosx_arm64/build/venv/lib/python3.8/site-packages/delocate/delocating.py", line 664, in delocate_wheel
      raise DelocationError(
  delocate.delocating.DelocationError: Some missing architectures in wheel
  Required arch arm64 missing from /Users/runner/work/prophet/prophet/python/build/lib.macosx-11.0-arm64-cpython-38/prophet/stan_model/cmdstan-2.33.1/stan/lib/stan_math/lib/tbb/libtbbmalloc_proxy.dylib
  Required arch arm64 missing from prophet/stan_model/cmdstan-2.33.1/stan/lib/stan_math/lib/tbb/libtbbmalloc_proxy.dylib
  Required arch arm64 missing from prophet/stan_model/prophet
  Required arch arm64 missing from prophet/stan_model/prophet_model.bin
```
[link](https://github.com/facebook/prophet/actions/runs/6468640060/job/17561081637).

Is this something you've seen before by any chance / do you know a patch? Otherwise we could try to use the unrepaired wheels, although from memory that didn't work last time when I saw a similar error.

**Comment by tcuongd** [comment]
Never mind, cibuildwheel uses cross-compiled Python 3.8 for ARM builds: https://cibuildwheel.readthedocs.io/en/stable/faq/#macos-building-cpython-38-wheels-on-arm64

Changing the Python version for the build to 3.9 works fine! https://github.com/facebook/prophet/actions/runs/6469124634/job/17562559766

**Comment by WardBrian** [comment]
🎉

**Comment by radeva** [comment]
@WardBrian @tcuongd You can try [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. They are on average 2x faster and 2x cheaper than GitHub's **AND** we have a **free tier for OSS projects** (see below).

# Install Instructions

1. Install [FlyCI app](https://github.com/apps/flyci-prod) and 
2. Easily replace one line of code and start using FlyCI runners:

```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```
# 500 mins/month Free for Public Repos

Since your repo is public, FlyCI offers **500 mins/month of free M1 runner usage** with the `flyci-macos-large-latest-m1` runner for public projects. 

Don't hesitate to contact us in case the free tier doesn't suit your needs or you experience any issues with the runners. Our team is here to support you!

Best Regards,
Veselina Radeva
Product Manager at [FlyCI](https://flyci.net/)

**Pull request merged**
