### PR TITLE
Add median absolute percent error to diagnostics (#911)

### PR DESCRIPTION
**Pull request by louispotok**

### CODE REVIEW

**Comment by bletham** [comment]
Thanks for the PR!
Unfortunately I just today pushed a significant change to how CV performance metrics are handled that impacts this PR.

The change is 269133c13342068f7bafcc134c610d085aa52ed6

and basically it makes it so that when computing the rolling average, we first aggregate over horizon and return a single estimate per unique value of horizon. The rolling window is only used for horizons that have <w samples.

I have a comment here that explains why the change was made and how the metrics are computed with the new approach: https://github.com/facebook/prophet/issues/839#issuecomment-462524968

The code that does the aggregation/mean is now quite a bit more complex than it was before, and does have some mean-specific features to it. So you'd need to refactor that to be able to use median.

**Comment by louispotok** [comment]
@bletham Ah! Unfortunate timing :-). 

At a first glance, it looks to me like adding a new function `rolling_median_by_h` would probably be the easiest way to mimic this behavior for medians and would not be too difficult. The `rolling_mean_by_h` function looks to have a lot of mean-specific behavior. Do you agree with that, or would you prefer a refactor to `rolling_agg_by_h` that then takes an argument for `mean` or `median` and shares more functionality?

**Comment by bletham** [comment]
I agree, the function is pretty mean-specific so a separate for the median would make sense.

The thing to be careful of is that all metrics must return results with the same set of horizon values (https://github.com/facebook/prophet/blob/master/python/fbprophet/diagnostics.py#L264). This seemed pretty safe right now since all metrics are computed using the same function, but once we have two functions it would be good to do something a little stricter there to avoid future bugs.

**Comment by louispotok** [comment]
@bletham closed this PR just for git housekeeping on my fork, will reopen once I know what we're doing.

Looking at this code, I don't know that there is a single principled way to do the median. What I understand we do for mean is use a weighted average of the x's with `h == h_i` and the x's with `h ==h_i_-1`, but I don't think that makes sense for median.

For example:

```
x = [1, 2, 4, 5 ,6]
h = [1, 1, 1, 2 ,2]
w = 3
```

To start, if I'm understanding this correctly, the return value should be `[2, 2, 2, a, b]`, right? And a == b?

So now the question is, how do we combine 5.5 (the median for `h=2`) with 2, the median for `h=1`? Does a weighted mean make sense as well? If so, since we need one point from `h=1`, the result should be `(1/3) * (2) + (2/3) * (5.5)`? Is that right?

**Comment by bletham** [comment]
Yeah, what is done for the means is the equivalent of the last, where we are adding a single data point to get it up to 3, but then taking the average over all of the ones we possibly could have taken.

For the mean that is fast because we can work out analytically what that average should be, but for the median it would probably be a bit obnoxious and I don't think is necessary. I think it would be OK to just walk back through `x` and take whatever the first ones are until we reach w, so in this case `[6, 5, 7]`. As an estimator it doesn't change the bias at all, perhaps just has a bit higher variance but I think in most situations there will be enough datapoints in that median that there won't be that much to gain by the avg(median()) approach, and so it would only be worth doing if you found it ended up being easy to implement and fast.

**Pull request closed without merging**
