### PR TITLE
Update python-holidays integration

### PR DESCRIPTION
**Pull request by arkid15r**
Hi there, I'm Ark. 
I maintain [python-holidays](https://github.com/dr-prodigy/python-holidays/).

Please consider this PR which aims to address multiple issues related to how prophet handles countries holidays.
Resolves https://github.com/facebook/prophet/issues/1202, https://github.com/facebook/prophet/issues/2011, https://github.com/facebook/prophet/issues/2063, https://github.com/facebook/prophet/issues/2326

The python-holidays v0.20 has been released recently. This version introduces l10n support and includes "extra" countries from `hdays.py`.

A summary of changes:

Bump python-holidays version to 0.20.

Migrate to python-holidays as a single source of country holidays:
  - Add Belarus holidays.
  - Add Bulgaria holidays.
  - Add Japan holidays.
  - Add Russia holidays.
  - Add Serbia holidays.
  - Add Ukraine holidays.
  - Add other ascii compatible countries holidays.
  - Update existing countries holidays.

Refactor `make_holidays.py`.
Refactor `generate_holidays_file.py`.

Generate new `generated_holidays.csv`.

Please note this PR does NOT contain documentation updates.

Let me know if you'd like to request any changes or add suggestions.
Thank you!

### CODE REVIEW

**Comment by tcuongd** [comment]
Hey so sorry I'm late to this, given the recent incompatibility I'll definitely take a look soon, it'd be amazing to use the holidays API properly.

**Comment by tcuongd** [comment]
This is great @arkid15r - thanks so much! We've explored replacing some of the classes in `hdays.py` before but found quite a few missing holidays for some countries; looks like that's no longer the case so huge props to your work in the holidays package! Some checks comparing main to this branch:

image

image

It seems like for India and Pakistan the differences are due to 1) name changes, which is fine, and 2) some Christian holidays being removed. I'm not too fussed about the latter, I think any potential problems can be addressed with guidance in the release notes (e.g. add custom holidays if necessary). I think the benefit of cleaner code and being able to rely on a single source of truth for holidays is greater than some potentially missed holidays localized to certain regions of IN / PK.

image

The code looks all good to me - I've just formatted according to black (which I'll start to use more throughout the repo) and refactored the generate holidays script a little to make it easier to compare changes between branches. 

I think the only other step is to deprecate `hdays.py` (I doubt many people are importing from that directly, but we'll deprecate over a couple of minor versions just in case).

**Review by tcuongd — APPROVED** [review]

**Comment by tcuongd** [comment]
R workflow failure is unrelated to these changes, will fix in a different PR.

**Comment by arkid15r** [comment]
Hey @tcuongd,
thanks for accepting this PR and providing thorough screenshots!

The python-holidays team's efforts resulted in a notable extension of the supported country list as well as better holiday coverage for each country. As for IN/PK I believe the current holiday list is the correct one. However, we'll gladly accept a PR/issue fixing or pointing out to any current/historical holidays discrepancy.

As a python-holidays maintainer I don't expect any major changes affecting prophet any time soon. You may expect one or two minor PRs later this year.

Also 👍  to the black formatting as I wasn't sure about the preferred style while working on this PR some time ago.

Thank you for the review and merging this!

**Pull request merged**
